GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'root' WITH GRANT OPTION;
GRANT ALL ON krampoline.* TO 'root'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE
    DATABASE krampoline DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
