spring:
  profiles:
    group:
      local:
        - local-mysql
        - local-token
      dev:
        - dev-mysql
        - dev-token
    active: dev
logging:
  level:
    org.springframework.web: DEBUG
    level.org.springframework.web.servlet.DispatcherServlet: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n %rEx{full}"