namespace: default
resources:
  - ingress.yaml
  - mariadb.yaml
  - deployment.yaml
  - configs/secrets.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
  - name: init-db
    files:
      - mysql-init.d/00_init.sql
      - mysql-init.d/01_create_table.sql
      - mysql-init.d/02_insert_data.sql
